In [156]:
import pandas as pd
from datetime import datetime

In [151]:


df = pd.read_excel(r"data-modeled-merged.xlsx")


In [182]:
df

Batch-Factor  Factor  Downtime_Minutes   Batch         Description  \
0         5000014       4                 9  500001  Inventory shortage   
1         5000044       4                10  500004  Inventory shortage   
2         5000036       6                21  500003  Machine adjustment   
3         5000037       7                17  500003     Machine failure   
4         5000071       1                28  500007      Emergency stop   
..            ...     ...               ...     ...                 ...   
995       5008912       2                30  500891        Batch change   
996       5008924       4                12  500892  Inventory shortage   
997       5008925       5                13  500892       Product spill   
998      50089212      12                 7  500892               Other   
999       5008952       2                68  500895        Batch change   

     Operator_Error      Date Product Operator          Start Time  \
0                 0  1/1/2025  DC-600    frank 1899-12-31 00:00:00   
1                 0  1/1/2025  DC-600  charlie 1899-12-31 03:47:00   
2                 1  1/1/2025  LE-600  charlie 1899-12-31 02:09:00   
3                 0  1/1/2025  LE-600  charlie 1899-12-31 02:09:00   
4                 0  1/1/2025   CO-2L   dennis 1899-12-31 09:59:00   
..              ...       ...     ...      ...                 ...   
995               1  3/3/2025  RB-600     ivan 1899-12-31 23:11:00   
996               0  3/4/2025  CO-600    frank 1899-12-31 00:41:00   
997               1  3/4/2025  CO-600    frank 1899-12-31 00:41:00   
998               0  3/4/2025  CO-600    frank 1899-12-31 00:41:00   
999               1  3/4/2025  RB-600    grace 1899-12-31 08:08:00   

               End Time      Flavor  Size  Min batch time Start-Time End-Time  \
0   1899-12-31 01:09:00   diet cola   600              60      00:00    01:09   
1   1899-12-31 04:57:00   diet cola   600              60      03:47    04:57   
2   1899-12-31 03:47:00  lemon lime   600              60      02:09    03:47   
3   1899-12-31 03:47:00  lemon lime   600              60      02:09    03:47   
4   1899-12-31 12:45:00        cola  2000              98      09:59    12:45   
..                  ...         ...   ...             ...        ...      ...   
995 1900-01-01 00:41:00  root berry   600              60      23:11    00:41   
996 1899-12-31 02:13:00        cola   600              60      00:41    02:13   
997 1899-12-31 02:13:00        cola   600              60      00:41    02:13   
998 1899-12-31 02:13:00        cola   600              60      00:41    02:13   
999 1899-12-31 10:39:00  root berry   600              60      08:08    10:39   

     Fact-Min-batch-time  
0                     69  
1                     70  
2                     98  
3                     98  
4                    166  
..                   ...  
995                   90  
996                   92  
997                   92  
998                   92  
999                  151  

[1000 rows x 17 columns]

In [178]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 17 columns):
 #   Column               Non-Null Count  Dtype         
---  ------               --------------  -----         
 0   Batch-Factor         1000 non-null   int64         
 1   Factor               1000 non-null   int64         
 2   Downtime_Minutes     1000 non-null   int64         
 3   Batch                1000 non-null   int64         
 4   Description          1000 non-null   object        
 5   Operator_Error       1000 non-null   int64         
 6   Date                 1000 non-null   object        
 7   Product              1000 non-null   object        
 8   Operator             1000 non-null   object        
 9   Start Time           1000 non-null   datetime64[ns]
 10  End Time             1000 non-null   datetime64[ns]
 11  Flavor               1000 non-null   object        
 12  Size                 1000 non-null   int64         
 13  Min batch time       1000 non-null

In [172]:
df.rename(columns={'Operator Error': 'Operator_Error'}, inplace=True)


In [173]:
df['Operator_Error'] = df['Operator_Error'].replace({'Yes': 1, 'No': 0})


In [176]:
df['Operator_Error']=df['Operator_Error'].astype(int)


In [177]:
df['Operator_Error'].unique()

array([0, 1])

In [145]:
df['Operator_Error'].unique()

array([0, 1])

In [167]:
df['Fact-Min-batch-time'].unique()

array([ 69,  70,  98, 166, 180, 122,  96, 125, 145, 114,  79,  99,  80,
       103, 108,  89, 199,  67, 155,  71, 118,  97, 113, 116, 126, 112,
       104,  75, 138, 124, 128,  84,  72, 132, 105, 102, 143, 127,  93,
        86, 120, 129, 134,  66, 100,  78, 149,  85, 135, 130, 110, 131,
        94,  95, 146, 101,  76, 107,  81, 141, 156, 121, 123,  87, 158,
       139, 142,  92,  91,  74,  68,  88, 167, 152, 140, 137,  65,  73,
       106, 119, 157,  82, 211, 117, 144, 133,  83,  90, 109, 136,  77,
       153, 111, 115, 165, 163, 160, 151, 162, 169, 168, 181, 150, 154,
       147, 174, 171, 188, 148, 161])

In [163]:
df['Size'] = df['Size'].str.replace(r'[^0-9.-]', '', regex=True)
df['Size'] = df['Size'].astype(int)


In [86]:
df.rename(columns={'Size': 'Size_ml'}, inplace=True)


In [90]:
df['Size_ml'].unique()


array([ 600, 2000])

In [181]:
df['Flavor'] = df['Flavor'].str.lower().str.strip()
df['Operator'] = df['Operator'].str.lower().str.strip()

In [155]:
df['Start Time'] = pd.to_datetime(df['Start Time'])
df['End Time'] = pd.to_datetime(df['End Time'])
df['Start-Time'] = df['Start Time'].dt.strftime('%H:%M')
df['End-Time'] = df['End Time'].dt.strftime('%H:%M')
#df['Time_24'] = df['Time'].dt.strftime('%H:%M:%S')

# df['Start Time'] = pd.to_datetime(df['Start Time'],format="%I:%M %p")
# df['End Time'] = pd.to_datetime(df['End Time'],format="%I:%M %p")
# df = df.drop('time', axis=1)
# df = df.drop('hour', axis=1)

# print(df)


C:\Users\laptop home\AppData\Local\Temp\ipykernel_7548\2085534481.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Start Time'] = pd.to_datetime(df['Start Time'])


In [165]:
df.loc[df['End Time'] < df['Start Time'], 'End Time'] += pd.Timedelta(days=1)
df['Duration'] = df['End Time'] - df['Start Time']


In [166]:
df['Fact-Min-batch-time'] = df['Duration'].dt.total_seconds() / 60
df['Fact-Min-batch-time']=df['Fact-Min-batch-time'].astype(int)

In [169]:
df = df.drop('Duration', axis=1)

In [160]:
df.duplicated().sum()

np.int64(0)

In [161]:
df.isna().sum()

Batch-Factor           0
Factor                 0
Downtime_Minutes       0
Batch                  0
Description            0
Operator_Error         0
Date                   0
Product                0
Operator               0
Start Time             0
End Time               0
Flavor                 0
Size                   0
Min batch time         0
Start-Time             0
End-Time               0
Fact-Min-batch-time    0
dtype: int64

In [8]:
#df['Date'] = pd.to_datetime(df['Date'])
#df['last_review'] = pd.to_datetime(df['last_review'], format='%Y-%m-%d')

In [183]:
df.columns

Index(['Batch-Factor', 'Factor', 'Downtime_Minutes', 'Batch', 'Description',
       'Operator_Error', 'Date', 'Product', 'Operator', 'Start Time',
       'End Time', 'Flavor', 'Size', 'Min batch time', 'Start-Time',
       'End-Time', 'Fact-Min-batch-time'],
      dtype='object')

In [188]:
df.to_excel('data_cleaned_prossesed.xlsx', index=False)